apiVersion: apps/v1
kind: Deployment
metadata:
  name: custom-ngin
  namespace: myapps
spec:
  replicas: 2
  selector:
    matchLabels:
      app: custom-ngin
  template:
    metadata:
      labels:
        app: custom-ngin
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
